### ISSUE TITLE
카카오 API 연동

### ISSUE THREAD

**Issue by HongRae-Kim** [HongRae-Kim/SW_5#7]
카카오 API 연동 후 streamlit에서 지도 정보가 나오게 구현해주세요.

**Comment by GithubOfHermes** [comment]
![API 연결2](https://github.com/user-attachments/assets/2f7ac382-400b-46a8-a654-af9db0f55a96)
카카오 API 연동 완료

**Comment by GithubOfHermes** [comment]
[카카오맵API 코드.txt](https://github.com/user-attachments/files/17985806/API.txt)
streamlit에 지도 구현 완료 
코드는 이전에 카카오톡으로 전달한 것과 동일함

금요일 때 수업 시간 전이라 PR할 시간이 부족해 txt파일로 카카오톡으로 전달했었습니다

**Comment by HongRae-Kim** [comment]
넵 지금 확인했습니다 나중에 PR 해주시면 될 것 같아요
